### ISSUE TITLE
Crate should be removed from pallet before unloading

### ISSUE THREAD

**Issue by erelson** [fetchrobotics/docs#12]
In the video at http://docs.fetchrobotics.com/in_the_box.html we do not mention the pallet that the crate (sometimes) ships on.  One important note is to remove the crate from the pallet before rolling the robot down the ramp, as while the crate is on the pallet, the ramp is at a steep angle that risks damaging skins.

@daviddymesich can we easily add a warning in the unpacking video? If not, we can add a warning before the video on the page.

**Comment by daviddymesich** [comment]
Since the people in the receiving department in various establishments won't watch the video, we decided not to include unloading from the pallet. We assume that they will get the ATA case on its casters to make it easier to push to its final destination without waiting for unpacking instructions.

If we find that it has become an issue, it can easily be added to the video.
